"""Create a new column called `revenue`:

revenue = quantity * unit_price

Display:
customer, product, quantity, unit_price, revenue
"""
import datetime

import pandas as pd
import numpy as np

file_path="/Users/prse/PycharmProjects/Python-Refresher/Python-Practice/Pandas/pandas_intermediate_practice_dataset.csv"
df=pd.read_csv(file_path)
df["revenue"]=df["quantity"]*df["unit_price"]
print(df[['customer','product','quantity','unit_price','revenue']])

# """Find all orders where:
#
# - quantity is greater than 5
# - status is "Delivered"
#
# Display the customer, product, quantity, and status.
# """


order_list=np.where((df["quantity"]>5) & (df["status"]=="Delivered"))[0]
# print(df.loc[(order_list),['customer','product','quantity','status']])
# print(order_list[['customer','product','quantity','status']])
print(df.loc[order_list, ["customer", "product", "quantity", "status"]])


""" Find all orders where:

- category is "Electronics"
- revenue is greater than 2000

Display the complete rows."""

order_ls=(df["category"]=="Electronics") & ((df["quantity"]*df["unit_price"]>2000))
print(f"the complete rows with electronics are {df[order_ls]}")

"""Calculate the total revenue generated by each region.

Expected output:

region | total_revenue
"""


df["total_revenue"]=df["quantity"]*df["unit_price"]
regions_val=df.groupby("region")["total_revenue"].sum()
print(regions_val)


"""For each product, calculate:

- total quantity sold
- average unit price
- total revenue
- number of orders
"""

total_quantity=df["quantity"].sum()
avg_unit_price=df["unit_price"].mean()
total_rev=(df["quantity"]*df["unit_price"]).sum()
no_of_orders=total_quantity
each_prod=df["product"]
tq=df.groupby("product")["quantity"].sum()
aup=df.groupby("product")["unit_price"].mean()
tr=df.groupby("product")["total_revenue"].sum()

# each_prod

"""Find the 5 orders with the highest revenue.

Display:

order_id, customer, product, quantity, revenue

Sort from highest to lowest revenue."""

top_5 = df.sort_values("revenue", ascending=False).head(5)
print(top_5[["order_id", "customer", "product", "quantity", "revenue"]])

"""Find the number of orders for each status.

Expected categories include:

Delivered
Shipped
Cancelled
Returned

Sort the result from most common to least common."""
df["status"].value_counts(ascending=False)
# res=df.groupby("status")["category"].value_counts(ascending=True)

"""Calculate total revenue for each customer.

Then find customers whose total revenue is greater than 2000.

Display:

customer | total_revenue"""

each_total=df.groupby("customer")["total_revenue"].sum().reset_index(name="total_revenue")
mask=each_total["total_revenue"]>2000
print(f"masked df {each_total[mask]}")

"""Convert `order_date` to a proper datetime column.

Find all orders placed during February 2026.

Display:

order_id, customer, order_date, product, revenue"""


df["order_date"]=pd.to_datetime(df["order_date"])
# print(proper_date)
# filtre= df.query('proper_date["order_date"]>  "2026-03-01"')
# print(filtre)
filt=df["order_date"]>"2026-03-01"
print(df.loc[filt,["order_id", "customer", "order_date", "product", "revenue","total_revenue"]])

"""Create a new column called `month` containing the month from
`order_date`.

Calculate total revenue for each month.

Expected output:

month | total_revenue

Sort chronologically.

"""
df["month"]=df["order_date"].dt.month
rev_by_month=(df.groupby("month")["revenue"].sum().reset_index(name="total_revenue"))
print(df["month"])
print(f" revenue by month is {rev_by_month}")

"""Calculate total revenue grouped by BOTH:

- region
- category

Expected structure:

region | category | total_revenue

Sort the results by total revenue in descending order.

"""

rev_cate=df.groupby(["region","category"])["revenue"].sum().reset_index(name="total_revenue").sort_values(ascending=False,by="total_revenue")
print(f"revenue by category {rev_cate}")


"""Calculate the percentage of total revenue contributed by each region.

Expected output:

region | total_revenue | revenue_percentage

The percentages should add up to approximately 100%."""

total_regions=df["region"].value_counts().sum()
print(total_regions)
df["revenue_percentage"]=(df["total_revenue"])/df["total_revenue"].sum()*100
print(df["revenue_percentage"])

"""For every region, determine which product generated the
highest total revenue.

Expected output:

region | product | total_revenue

Hint:
You may need to use:

groupby()
sort_values()
drop_duplicates()

or another appropriate approach."""

high_prod=(df.groupby(["region","product"])["total_revenue"].sum().reset_index(name="total_revenue")).sort_values(["region", "total_revenue"], ascending=[True, False]).drop_duplicates("region")
print(f"product with highest revenue are {high_prod}")

"""Create a pivot table showing total revenue by:

Rows:
    region

Columns:
    category

Values:
    revenue

Expected structure:

              Accessories   Electronics   Furniture
East          ...
North         ...
South         ...
West          ...

Add row and column totals if you can."""

res=df.pivot_table(index=['region'],columns='category',values='revenue',aggfunc='sum',margins=True)
print(f"pivot table is {res}")

""""""